### ISSUE TITLE
Question: Will functionality presented at ROSCon 2018 be available for the ROS1 version of nav_core2?

### ISSUE THREAD

**Issue by kajep09** [locusrobotics/robot_navigation#11]
Hello @DLu and thank you for the interesting talk at ROSCon 2018.

For me it remains unclear whether all (or some) of the functionality that you presented will be available in the ROS1 version of the package or will it only be for the reimplementation of the navigation stack for ROS2  / https://github.com/ros-planning/navigation2.

Furthermore, even if the functionality won't be implemented in this version of the package, can we assume that the interfaces will stay the same so that we will be able to e.g. reuse DWB critics in the future when/if navigation2 ends up in the December release of ROS2.

Sorry for asking a generic question on the issue page, but I imagine that a lot of people will visit this github link after watching your talk, and the information is not available anywhere.

Thank you!

**Comment by DLu** [comment]
Code is now released!
