### ISSUE TITLE
Cmake::policy CMP0002 Error

### ISSUE THREAD

**Issue by sweetquiet** [locusrobotics/robot_navigation#21]
When compiling, two cmakelists will use the same name, resulting in compilation errors, such as utest,planner_node,Only by changing one name can we compile and pass

**Comment by DLu** [comment]
Can you give more details about what distro you're using, what OS, and what command you're running?

**Comment by sweetquiet** [comment]
Hello, my operating system is: Ubuntu 16.04, the program is github-master, ROS is kinetic, compiler will report that cmake error, but now change to another name okay, now runtime found obstacles can not be removed in time.

**Comment by DLu** [comment]
Please provide the compile command you're running (catkin_make or catkin build or whatever) and the exact error text you're seeing.

**Comment by sweetquiet** [comment]
First of all, thank you very much for your reply! Obstacles can not be cleared in time did not appear again, this navigation package I can also operate normally, I will close this problem soon, thank you again.
