### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mintar** [locusrobotics/robot_navigation#28]
Hi David, it would be nice if we could get a new release, so that #25 is included. At the moment, all the binary releases are broken due to the bug that #25 fixed. Here's a typical example:
![bildschirmfoto_2019-01-25_11-48-38](https://user-images.githubusercontent.com/320188/51981973-fa067e00-2494-11e9-9cd3-4a6122fcbe4f.png)

**Comment by mintar** [comment]
Oh, and c24cfa9 should also be cherry-picked onto the tf2 branch.

**Comment by DLu** [comment]
[I](https://github.com/ros/rosdistro/pull/20285) J [K](https://github.com/ros/rosdistro/pull/20293) [L](https://github.com/ros/rosdistro/pull/20294) (M pending)
