### ISSUE TITLE
map

### ISSUE THREAD

**Issue by cckx1234** [locusrobotics/robot_navigation#41]
请问你这个导航是基于高程地图做的导航吗，还是二维珊格地图

**Comment by DLu** [comment]
Google translate says: Can you use this navigation based on elevation maps or two-dimensional maps?

This code is intended for 2.5 dimensional navigation, i.e. just using x, y and theta. That does not include elevation, so the answer to the first part is no. I'm not clear what you mean by two-dimensional maps. 

Google翻译说：此代码适用于2.5维导航，即仅使用x，y和theta。 这不包括高程，所以第一部分的答案是否定的。 我不清楚二维地图的意思。

**Comment by artemiialessandrini** [comment]
@cckx1234 这是二维珊格地图导航, 不是3D的
