### ISSUE TITLE
crashing with MapGridCritics

### ISSUE THREAD

**Issue by naveedhd** [locusrobotics/robot_navigation#6]
Critics based on `MapGridCritics` crashed in prepare causing `local_planner/move_base` to crash.

On looking a bit in, it has something to do with `propogateManhattanDistance`/`costmap_queue`, but wasn't able to look deeper.

**Comment by DLu** [comment]
@naveedhd @sjphilli I've updated the CostmapQueue package [here](https://github.com/locusrobotics/robot_navigation/commit/b42ec7f26e4619f83e3e9e9fd729699d52f1410c) to a new version that has been more extensively tested. Can you let me know if it fixes your problems?

**Comment by naveedhd** [comment]
a co-worker is trying out and seems to be fixed! closing the issue.
