### ISSUE TITLE
Failed to build locomotor package by using catkin_make_isolated --install --use-ninja

### ISSUE THREAD

**Issue by ThaparPiyush** [locusrobotics/robot_navigation#63]
Hi, I am unable to build locomotor package while using catkin_make_isolated --install --use-ninja. Error its showing up is NavCore2Exception Ptr' is not a member of 'nav_core2'

**Comment by DLu** [comment]
Which distro and branch of this repo are you using? Please post the full error log.

**Comment by DLu** [comment]
Closing in favor of https://answers.ros.org/question/359231/failed-to-build-locomotor-package-by-using-catkin_make_isolated-install-use-ninja/
