### ISSUE TITLE
multi-robot

### ISSUE THREAD

**Issue by xbcdbc** [locusrobotics/robot_navigation#69]
does it suport multi-robot

**Comment by DLu** [comment]
Locus Robotics has many robots at the same site running this code. However, there is not explicit support for synchronizing motions across multiple robots. That sort of thing can be done via plugins.

**Comment by xbcdbc** [comment]
I see the video of Locus Robotics，the localization of the robot only depend on visual apriltag?Does it make use of the 2D laser?
