### ISSUE TITLE
Acceleration limit for backward driving

### ISSUE THREAD

**Issue by Thazz** [locusrobotics/robot_navigation#71]
When applying acceleration/deceleration limits in velocity iterator, one should be looking for difference in velocity magnitude (absolute value).

https://github.com/locusrobotics/robot_navigation/blob/a17dd62fed2fac6a011fe1220308933712e5491d/dwb_plugins/include/dwb_plugins/one_d_velocity_iterator.h#L56-L69

Currently, If the robot is driving backwards and its velocity changes from e.g `v0 = -1 m/s` to `target = -1.5 m/s`, deceleration limit is used (as `v0 > target`), although robot is actually accelerating. The same goes for deceleration.

I can provide PR if needed.

**Comment by DLu** [comment]
Makes sense! Please make a PR.
